#!/usr/bin/env python3
"""Embed binary assets (banner, music, Linux window icons) into assets.c/assets.h.

Run from the repo root: python3 src/assets_gen.py
Icon PNGs come from src/icons_gen.sh (SVG master -> sized PNGs + .ico).
"""
import os

ASSETS = {
    "banner_gif": "src/assets/banner.gif",
    "music_xm":   "src/assets/music.xm",
    "icon_32":    "src/assets/icon/sct_32.png",
    "icon_64":    "src/assets/icon/sct_64.png",
    "icon_256":   "src/assets/icon/sct_256.png",
}

def c_array(name: str, data: bytes) -> str:
    out = [f"const unsigned char {name}[] = {{"]
    for i in range(0, len(data), 16):
        chunk = ", ".join(f"0x{b:02x}" for b in data[i:i+16])
        out.append(f"    {chunk},")
    out.append("};")
    return "\n".join(out)

def main() -> None:
    src_c = ["/* Generated by assets_gen.py -- do not edit. */", "#include \"assets.h\"", ""]
    src_h = ["/* Generated by assets_gen.py -- do not edit. */",
             "#ifndef SCT_ASSETS_H", "#define SCT_ASSETS_H", "",
             "#ifdef __cplusplus", "extern \"C\" {", "#endif", ""]

    for name, path in ASSETS.items():
        size = os.path.getsize(path)
        with open(path, "rb") as f:
            data = f.read()
        print(f"{name}: {path} -> {size} bytes")
        src_c.append(c_array(name, data))
        src_c.append(f"const unsigned int {name}_len = {size};")
        src_c.append("")
        src_h.append(f"extern const unsigned char {name}[];")
        src_h.append(f"extern const unsigned int {name}_len;")

    src_h += ["", "#ifdef __cplusplus", "}", "#endif", "", "#endif /* SCT_ASSETS_H */", ""]

    with open("src/assets.c", "w") as f:
        f.write("\n".join(src_c) + "\n")
    with open("src/assets.h", "w") as f:
        f.write("\n".join(src_h) + "\n")
    print("wrote src/assets.c src/assets.h")

if __name__ == "__main__":
    main()
