/* Generated by assets_gen.py -- do not edit. */
#ifndef SCT_ASSETS_H
#define SCT_ASSETS_H

#ifdef __cplusplus
extern "C" {
#endif

extern const unsigned char banner_gif[];
extern const unsigned int banner_gif_len;
extern const unsigned char music_xm[];
extern const unsigned int music_xm_len;
extern const unsigned char icon_32[];
extern const unsigned int icon_32_len;
extern const unsigned char icon_64[];
extern const unsigned int icon_64_len;
extern const unsigned char icon_256[];
extern const unsigned int icon_256_len;

#ifdef __cplusplus
}
#endif

#endif /* SCT_ASSETS_H */

